server:
  port: 11011

logging:
  config: classpath:logback-springboot.xml

# https://liteflow.yomahub.com/pages/4594ec/
liteflow:
  support-multiple-type: true
  enable: true
  print-banner: false
  parse-on-start: true
  rule-source: rules/liteflow-yml-type.el.yml,rules/liteflow-xml-type.el.xml,rules/liteflow-script-component.el.xml
  print-execution-log: true
  monitor:
    enable-log: true
    queue-limit: 200
    delay: 60000
    period: 60000

print-server-address:
  prefix: --->
  suffix: <---