server:
  port: 11011

logging:
  config: classpath:logback-springboot.xml

# https://liteflow.yomahub.com/pages/4594ec/
liteflow:
  enable: true
  main-executor-works: 4
  when-max-workers: 4
  when-queue-limit: 1024
  when-max-wait-time-unit: seconds
  when-max-wait-time: 60
  support-multiple-type: true
  print-banner: false
  parse-mode: ${LF_DEMO_PARSE_MODE:PARSE_ONE_ON_FIRST_EXEC}
  rule-source: rules/liteflow-yml-type.el.yml,rules/liteflow-xml-type.el.xml,rules/liteflow-script-component.el.xml
  print-execution-log: true
  monitor:
    enable-log: true
    queue-limit: 200
    delay: 60000
    period: 60000

print-server-address:
  prefix: --->
  suffix: <---
