### /liteflow/execute2Resp/chain1
GET http://localhost:11011/liteflow/execute2Resp/chain1

### /liteflow/execute2Resp/chainRepeat
GET http://localhost:11011/liteflow/execute2Resp/chainRepeat

### /liteflow/execute2Resp/chain-xml
GET http://localhost:11011/liteflow/execute2Resp/chain-xml

### /liteflow/execute2Resp/chain-switch
GET http://localhost:11011/liteflow/execute2Resp/chain-switch

### /liteflow/execute2Resp/chain-script
GET http://localhost:11011/liteflow/execute2Resp/chain-script

### /liteflow/execute2Resp/concurrentRecordFlow
GET http://localhost:11011/liteflow/execute2Resp/concurrentRecordFlow

### /liteflow/dynamic/createChain
POST http://localhost:11011/liteflow/dynamic/createChain
Content-Type: application/json

{
  "chainId": "dynamicChainScript",
  "el": "THEN(dynamicScript1,dynamicScript2)"
}

### /liteflow/chain/validate
POST http://localhost:11011/liteflow/chain/validate
Content-Type: application/json

{
  "el": "//this is a test\nTHEN(a, b, h)\n"
}

### /liteflow/execute2Resp/dynamicChainScript
GET http://localhost:11011/liteflow/execute2Resp/dynamicChainScript

### /liteflow/execute2Resp/switchChainTest
GET http://localhost:11011/liteflow/execute2Resp/switchChainTest

### /liteflow/execute2Resp/whileChain
GET http://localhost:11011/liteflow/execute2Resp/whileChain

### /liteflow/execute2Resp/forChain
GET http://localhost:11011/liteflow/execute2Resp/forChain

### /liteflow/getNodesByChainId
GET http://localhost:11011/liteflow/getNodesByChainId?chainId=chain1

### /liteflow/execute2Resp/invokeFuncInAviatorChainTest
GET http://localhost:11011/liteflow/execute2Resp/invokeFuncInAviatorChainTest

### /liteflow/execute2Resp/invokeFuncInJsChainTest
GET http://localhost:11011/liteflow/execute2Resp/invokeFuncInJsChainTest

### /liteflow/reloadChain
POST http://localhost:11011/liteflow/reloadChain
Content-Type: application/x-www-form-urlencoded

chainId=xx&elContent=xxx

### /liteflow/removeChain
POST http://localhost:11011/liteflow/removeChain
Content-Type: application/x-www-form-urlencoded

chainId=xx

### /liteflow/execute2Resp/invokeOtherChainTest
GET http://localhost:11011/liteflow/execute2Resp/invokeOtherChainTest
