### /liteflow/execute2Resp/hello
GET http://localhost:11011/liteflow/execute2Resp/hello

### /liteflow/execute2Resp/chain1
GET http://localhost:11011/liteflow/execute2Resp/chain1

### /liteflow/execute2Resp/chain-xml
GET http://localhost:11011/liteflow/execute2Resp/chain-xml

### /liteflow/execute2Resp/chain-switch
GET http://localhost:11011/liteflow/execute2Resp/chain-switch

### /liteflow/execute2Resp/chain-script
GET http://localhost:11011/liteflow/execute2Resp/chain-script

### /liteflow/reloadScript
GET http://localhost:11011/liteflow/reloadScript?nodeId=scriptStep1&script=console.log("hello world");