### /liteflow/reloadScript
GET http://localhost:11011/liteflow/reloadScript?nodeId=scriptStep1&script=console.log("hello world");

### /liteflow/script/validate
POST http://localhost:11011/liteflow/script/validate
Content-Type: application/json

{
  "language": "aviator",
  "script": "1+1a"
}

### /liteflow/dynamic/createScriptNode1
POST http://localhost:11011/liteflow/dynamic/createScriptNode
Content-Type: application/json

{
  "id": "dynamicScript1",
  "name": "dynamic script node component 1",
  "language": "groovy",
  "script": "import cn.netbuffer.liteflow.demo.pojo.Task\ndefaultContext.setData(\"task\",new Task(\"1.0032\",\"2.0087\",\"\"))"
}

### /liteflow/dynamic/createScriptNode2
POST http://localhost:11011/liteflow/dynamic/createScriptNode
Content-Type: application/json

{
  "id": "dynamicScript2",
  "name": "dynamic script node component 2",
  "language": "groovy",
  "script": "println \"before:\"+defaultContext.getData(\"task\")\ndef task=defaultContext.getData(\"task\")\ntask.setNum3(new BigDecimal(task.getNum1()).add(new BigDecimal(task.getNum2())).add(new BigDecimal(100)).toString())\ndefaultContext.setData(\"task\",task)\nprintln \"after:\"+defaultContext.getData(\"task\")"
}
